next_down_pos:
  description: Moves a blind group down to the next defined intermediate position
  target:
    entity:
      domain: cover
      integration: leviosa_shades

next_up_pos:
  description: Moves a blind group up to the next defined intermediate position
  target:
    entity:
      domain: cover
      integration: leviosa_shades
